-- MySQL Script generated by MySQL Workbench
-- Fri Jul 29 16:32:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `emai` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `emai_UNIQUE` (`emai` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bank_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bank_account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bank_account` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `iban` VARCHAR(45) NOT NULL,
  `bic` VARCHAR(45) NOT NULL,
  `balance` FLOAT NOT NULL DEFAULT 0,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `iban_bic_UNIQUE` (`iban` ASC, `bic` ASC) VISIBLE,
  INDEX `fk_bank_account_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_bank_account_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transaction_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transaction_type` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `type_name_UNIQUE` (`type_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sender` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sender` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`merchant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`merchant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`merchant` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_code` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `country_code` BIGINT NOT NULL,
  `visa_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `mid_UNIQUE` (`visa_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `amount` FLOAT NOT NULL,
  `description` VARCHAR(65) NULL,
  `bank_account_id` BIGINT NOT NULL,
  `transaction_type_id` BIGINT NOT NULL,
  `sender_id` BIGINT NULL,
  `merchant_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_transaction_bank_account1_idx` (`bank_account_id` ASC) VISIBLE,
  INDEX `fk_transaction_transaction_type1_idx` (`transaction_type_id` ASC) VISIBLE,
  INDEX `fk_transaction_sender1_idx` (`sender_id` ASC) VISIBLE,
  INDEX `fk_transaction_merchant1_idx` (`merchant_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_bank_account1`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `mydb`.`bank_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_transaction_type1`
    FOREIGN KEY (`transaction_type_id`)
    REFERENCES `mydb`.`transaction_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_sender1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `mydb`.`sender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_merchant1`
    FOREIGN KEY (`merchant_id`)
    REFERENCES `mydb`.`merchant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
